- name: Adding cgroup_enable=memory to boot parameters for k3s
  lineinfile:
    path: /boot/firmware/cmdline.txt
    state: present
    regexp: '^((?!.*cgroup_enable=memory).*console.*)$'
    line: '\1 cgroup_enable=memory'
    backrefs: yes
  notify: reboot

- name: Adding cgroup_memory=1 to boot parameters for K3s
  lineinfile:
    path: /boot/firmware/cmdline.txt
    state: present
    regexp: '^((?!.*cgroup_memory=1).*console.*)$'
    line: '\1 cgroup_memory=1'
    backrefs: yes
  notify: reboot

